<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Slider' => 'Новый слайд',
    'Dashboard' => 'Панель',
    'Order ID' => '',
    'Product ID' => '',
    'Slider' => 'Слайд',
    'Sliders' => 'Слайды',
    'Active' => 'Вкл/Выкл',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот пункт?',
    'Available' => 'В наличии',
    'Categories' => 'Категории',
    'Category' => 'Категория',
    'Category ID' => 'Название категории',
    'Category {$model->name} added' => 'Категория {$model->name} добавлена',
    'Close' => 'Закрытые',
    'Column' => 'Столбец',
    'Content' => 'Материал',
    'Create' => 'Создать',
    'Create Category' => 'Создать категорию',
    'Create Order' => 'Создать заказ',
    'Create Product' => 'Создать товар',
    'Date create' => 'Дата создания',
    'Date update' => 'Дата изменения',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Gallery' => 'Галерея',
    'ID' => '№',
    'Images' => 'Изображения',
    'Keywords' => 'Ключевые слова',
    'Meta data' => 'Мета данные',
    'Name' => 'Название',
    'Not available' => 'Нет в наличии',
    'Open' => 'Открытые',
    'Order' => 'Заказ',
    'Order status' => 'Статус',
    'Orders' => 'Заказы',
    'Parent ID' => 'Название категории',
    'Parent category' => 'Родительская категория',
    'Photo' => 'Фотография',
    'Price' => 'Цена',
    'Product name' => 'Название товара',
    'Product price' => 'Цена',
    'Product quantity' => 'Количество',
    'Product sum' => 'Сумма',
    'Products' => 'Товары',
    'Quantity' => 'Количество',
    'Root category' => 'Корневая категория',
    'Sum' => 'Стоимость заказа',
    'Update' => 'Изменить',
    'Update {modelClass}: ' => 'Изменение {modelClass}: ',
    'User address' => 'Адрес заказчика',
    'User email' => 'email заказчика',
    'User name' => 'Имя заказчика',
    'User phone' => 'Телефон заказчика',
    'Vcode' => 'Артикул',
    'View order: ' => 'Просмотр заказа: ',
];
